---
title: 'Model 1'
author: "Group 10" 
output:
  pdf_document:
---

## Load in Libaries
```{r}
library(tidyverse)
library(caret)
library(tidytext)
library(fastDummies)
```

## Reading in the Dataframe
```{r}
wine <- readRDS(gzcon(url("https://github.com/cd-public/D505/raw/master/dat/model.rds")))
```


## Tidy Text
```{r}
library(tidytext)
wine_desc <- wine %>%
  filter(province == "Oregon") %>%
  unnest_tokens(word, description) %>%
  anti_join(stop_words) %>%
  count(word) %>%
  arrange(desc(n)) %>%
  mutate(prop = n / sum(n))

wine_desc
```
```{r}
library(dplyr)

wine %>%
  distinct(province)
```


## Engineering Features

```{r}
library(tidyverse)
library(stringr)

wino <- wine %>%
  mutate(fct_year = factor(year),
         description = tolower(description)) %>%
  mutate(cherry = str_detect(description, "cherry"),
         chocolate = str_detect(description, "chocolate"),
         earth = str_detect(description, "earth"),
         oak = str_detect(description, "oak"),
         aroma = str_detect(description, "aroma"),
         dark = str_detect(description, "dark"),
         berry = str_detect(description, "berry"),
         spice = str_detect(description, "spice"),
         floral = str_detect(description, "floral"),
         vanilla = str_detect(description, "vanilla"),
         pepper = str_detect(description, "pepper"),
         fruit = str_detect(description, "fruit"),
         balance = str_detect(description, "balance"),
         acidity = str_detect(description, "acidity"),
         complex = str_detect(description, "complex"),
         nose = str_detect(description, "nose"),
         light = str_detect(description, "light"),
         raspberry = str_detect(description, "raspberry"),
         cranberry = str_detect(description, "cranberry"),
         alert = str_detect(description, "alert"),
         allergic = str_detect(description, "allergic"),
         acids = str_detect(description, "acids"),
         willamette = str_detect(description, "willamette"),
         stiff = str_detect(description, "stiff"),
         details = str_detect(description, "details"),
         lick = str_detect(description, "lick"),
         beaune = str_detect(description, "beaune"),
         nuits = str_detect(description, "nuits"),
         georges = str_detect(description, "georges"),
         chambertin = str_detect(description, "chambertin"),
         dundee = str_detect(description, "dundee"),
         aeration = str_detect(description, "aeration"),
         grounds = str_detect(description, "grounds"),
         proportionate = str_detect(description, "proportionate"),
         slate = str_detect(description, "slate"),
         sagebrush = str_detect(description, "sagebrush"),
         chaparral = str_detect(description, "chaparral"),
         sipped = str_detect(description, "sipped"),
         peppercorns = str_detect(description, "peppercorns"),
         waves = str_detect(description, "waves"),
         feral = str_detect(description, "feral"),
         mace = str_detect(description, "mace"),
         appetizing = str_detect(description, "appetizing"),
         study = str_detect(description, "study")) %>%
  mutate(cherry_year = year * cherry, 
         chocolate_year = year * chocolate,
         earth_year = year * earth,
         oak_year = year * oak,
         aroma_year = year * aroma, 
         dark_year = year * dark,
         berry_year = year * berry,
         spice_year = year * spice,
         floral_year = year * floral,
         vanilla_year = year * vanilla,
         pepper_year = year * pepper,
         fruit_year = year * fruit,
         balance_year = year * balance,
         acidity_year = year * acidity,
         complex_year = year * complex,
         nose_year = year * nose,
         light_year = year * light,
         raspberry_year = year * raspberry,
         cranberry_year = year * cranberry,
         alert_year = year * alert,
         allergic_year = year * allergic,
         acids_year = year * acids,
         willamette_year = year * willamette,
         stiff_year = year * stiff,
         details_year = year * details,
         lick_year = year * lick,
         beaune_year = year * beaune,
         nuits_year = year * nuits,
         georges_year = year * georges,
         chambertin_year = year * chambertin,
         dundee_year = year * dundee,
         aeration_year = year * aeration,
         grounds_year = year * grounds,
         proportionate_year = year * proportionate,
         slate_year = year * slate,
         sagebrush_year = year * sagebrush,
         chaparral_year = year * chaparral,
         sipped_year = year * sipped,
         peppercorns_year = year * peppercorns,
         waves_year = year * waves,
         feral_year = year * feral,
         mace_year = year * mace,
         appetizing_year = year * appetizing,
         study_year = year * study
        ) %>%
  select(-description)
```

## Save the dataframe

```{r}
write_rds(wine, file="group_n_knn.rds")
```

## Building KNN Model
```{r}
#set.seed(93129)
set.seed(43) #0.5459 
wine <- readRDS("group_n_knn.rds")
split <- createDataPartition(wino$province, p = 0.8, list = FALSE)
train <- wino[split, ]
test <- wino[-split, ]
fit <- train(province ~ .,
             data = train, 
             method = "knn",
             metric = "Kappa",
             trControl = trainControl(method = "cv", number = 5))

confusionMatrix(predict(fit, test),factor(test$province))
```





